//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss.Web.Auth.OpenId.Behaviors {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BehaviorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BehaviorStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.Web.Auth.OpenId.Behaviors.BehaviorStrings", typeof(BehaviorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The PAPE request has an incomplete set of authentication policies. 的本地化字符串。
        /// </summary>
        internal static string PapeRequestMissingRequiredPolicies {
            get {
                return ResourceManager.GetString("PapeRequestMissingRequiredPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A PAPE response is missing or is missing required policies. 的本地化字符串。
        /// </summary>
        internal static string PapeResponseOrRequiredPoliciesMissing {
            get {
                return ResourceManager.GetString("PapeResponseOrRequiredPoliciesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No personally identifiable information should be included in authentication responses when the PAPE authentication policy http://www.idmanagement.gov/schema/2009/05/icam/no-pii.pdf is present. 的本地化字符串。
        /// </summary>
        internal static string PiiIncludedWithNoPiiPolicy {
            get {
                return ResourceManager.GetString("PiiIncludedWithNoPiiPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No personally identifiable information should be requested when the http://www.idmanagement.gov/schema/2009/05/icam/no-pii.pdf PAPE policy is present. 的本地化字符串。
        /// </summary>
        internal static string PiiRequestedWithNoPiiPolicy {
            get {
                return ResourceManager.GetString("PiiRequestedWithNoPiiPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No PPID provider has been configured. 的本地化字符串。
        /// </summary>
        internal static string PpidProviderNotGiven {
            get {
                return ResourceManager.GetString("PpidProviderNotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discovery on the Realm URL MUST be performed before sending a positive assertion. 的本地化字符串。
        /// </summary>
        internal static string RealmDiscoveryNotPerformed {
            get {
                return ResourceManager.GetString("RealmDiscoveryNotPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Realm in an authentication request must be an HTTPS URL. 的本地化字符串。
        /// </summary>
        internal static string RealmMustBeHttps {
            get {
                return ResourceManager.GetString("RealmMustBeHttps", resourceCulture);
            }
        }
    }
}
