//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss.Web.Auth.OpenId {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OpenIdStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenIdStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.Web.Auth.OpenId.OpenIdStrings", typeof(OpenIdStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An absolute URI is required for this value. 的本地化字符串。
        /// </summary>
        internal static string AbsoluteUriRequired {
            get {
                return ResourceManager.GetString("AbsoluteUriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is already a PPID Identifier. 的本地化字符串。
        /// </summary>
        internal static string ArgumentIsPpidIdentifier {
            get {
                return ResourceManager.GetString("ArgumentIsPpidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested association type &apos;{0}&apos; with session type &apos;{1}&apos; is unrecognized or not supported by this Provider due to security requirements. 的本地化字符串。
        /// </summary>
        internal static string AssociationOrSessionTypeUnrecognizedOrNotSupported {
            get {
                return ResourceManager.GetString("AssociationOrSessionTypeUnrecognizedOrNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of the shared secret ({0}) does not match the length required by the association type (&apos;{1}&apos;). 的本地化字符串。
        /// </summary>
        internal static string AssociationSecretAndTypeLengthMismatch {
            get {
                return ResourceManager.GetString("AssociationSecretAndTypeLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of the encrypted shared secret ({0}) does not match the length of the hashing algorithm ({1}). 的本地化字符串。
        /// </summary>
        internal static string AssociationSecretHashLengthMismatch {
            get {
                return ResourceManager.GetString("AssociationSecretHashLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No association store has been given but is required for the current configuration. 的本地化字符串。
        /// </summary>
        internal static string AssociationStoreRequired {
            get {
                return ResourceManager.GetString("AssociationStoreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If an association store is given, a nonce store must also be provided. 的本地化字符串。
        /// </summary>
        internal static string AssociationStoreRequiresNonceStore {
            get {
                return ResourceManager.GetString("AssociationStoreRequiresNonceStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An attribute with type URI &apos;{0}&apos; has already been added. 的本地化字符串。
        /// </summary>
        internal static string AttributeAlreadyAdded {
            get {
                return ResourceManager.GetString("AttributeAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only {0} values for attribute &apos;{1}&apos; were requested, but {2} were supplied. 的本地化字符串。
        /// </summary>
        internal static string AttributeTooManyValues {
            get {
                return ResourceManager.GetString("AttributeTooManyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The private data supplied does not meet the requirements of any known Association type.  Its length may be too short, or it may have been corrupted. 的本地化字符串。
        /// </summary>
        internal static string BadAssociationPrivateData {
            get {
                return ResourceManager.GetString("BadAssociationPrivateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} extension failed to deserialize and will be skipped.  {1} 的本地化字符串。
        /// </summary>
        internal static string BadExtension {
            get {
                return ResourceManager.GetString("BadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Callback arguments are only supported when a {0} is provided to the {1}. 的本地化字符串。
        /// </summary>
        internal static string CallbackArgumentsRequireSecretStore {
            get {
                return ResourceManager.GetString("CallbackArgumentsRequireSecretStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Simple Registration request can only generate a response on the receiving end. 的本地化字符串。
        /// </summary>
        internal static string CallDeserializeBeforeCreateResponse {
            get {
                return ResourceManager.GetString("CallDeserializeBeforeCreateResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The openid.claimed_id and openid.identity parameters must both be present or both be absent. 的本地化字符串。
        /// </summary>
        internal static string ClaimedIdAndLocalIdMustBothPresentOrAbsent {
            get {
                return ResourceManager.GetString("ClaimedIdAndLocalIdMustBothPresentOrAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ClaimedIdentifier property cannot be set when IsDelegatedIdentifier is true to avoid breaking OpenID URL delegation. 的本地化字符串。
        /// </summary>
        internal static string ClaimedIdentifierCannotBeSetOnDelegatedAuthentication {
            get {
                return ResourceManager.GetString("ClaimedIdentifierCannotBeSetOnDelegatedAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This OpenID exploits features that this relying party cannot reliably verify.  Please try logging in with a human-readable OpenID or from a different OpenID Provider. 的本地化字符串。
        /// </summary>
        internal static string ClaimedIdentifierDefiesDotNetNormalization {
            get {
                return ResourceManager.GetString("ClaimedIdentifierDefiesDotNetNormalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ClaimedIdentifier property must be set first. 的本地化字符串。
        /// </summary>
        internal static string ClaimedIdentifierMustBeSetFirst {
            get {
                return ResourceManager.GetString("ClaimedIdentifierMustBeSetFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An extension with this property name (&apos;{0}&apos;) has already been registered. 的本地化字符串。
        /// </summary>
        internal static string ClientScriptExtensionPropertyNameCollision {
            get {
                return ResourceManager.GetString("ClientScriptExtensionPropertyNameCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The extension &apos;{0}&apos; has already been registered. 的本地化字符串。
        /// </summary>
        internal static string ClientScriptExtensionTypeCollision {
            get {
                return ResourceManager.GetString("ClientScriptExtensionTypeCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An authentication request has already been created using CreateRequest(). 的本地化字符串。
        /// </summary>
        internal static string CreateRequestAlreadyCalled {
            get {
                return ResourceManager.GetString("CreateRequestAlreadyCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only OpenIDs issued directly by their OpenID Provider are allowed here. 的本地化字符串。
        /// </summary>
        internal static string DelegatingIdentifiersNotAllowed {
            get {
                return ResourceManager.GetString("DelegatingIdentifiersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The associate request instance must be a Diffie-Hellman instance. 的本地化字符串。
        /// </summary>
        internal static string DiffieHellmanAssociationRequired {
            get {
                return ResourceManager.GetString("DiffieHellmanAssociationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following properties must be set before the Diffie-Hellman algorithm can generate a public key: {0} 的本地化字符串。
        /// </summary>
        internal static string DiffieHellmanRequiredPropertiesNotSet {
            get {
                return ResourceManager.GetString("DiffieHellmanRequiredPropertiesNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URI is not SSL yet requireSslDiscovery is set to true. 的本地化字符串。
        /// </summary>
        internal static string ExplicitHttpUriSuppliedWithSslRequirement {
            get {
                return ResourceManager.GetString("ExplicitHttpUriSuppliedWithSslRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An extension sharing namespace &apos;{0}&apos; has already been added.  Only one extension per namespace is allowed in a given request. 的本地化字符串。
        /// </summary>
        internal static string ExtensionAlreadyAddedWithSameTypeURI {
            get {
                return ResourceManager.GetString("ExtensionAlreadyAddedWithSameTypeURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot lookup extension support on a rehydrated ServiceEndpoint. 的本地化字符串。
        /// </summary>
        internal static string ExtensionLookupSupportUnavailable {
            get {
                return ResourceManager.GetString("ExtensionLookupSupportUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fragment segments do not apply to XRI identifiers. 的本地化字符串。
        /// </summary>
        internal static string FragmentNotAllowedOnXRIs {
            get {
                return ResourceManager.GetString("FragmentNotAllowedOnXRIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The HTML head tag must include runat=&quot;server&quot;. 的本地化字符串。
        /// </summary>
        internal static string HeadTagMustIncludeRunatServer {
            get {
                return ResourceManager.GetString("HeadTagMustIncludeRunatServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ClaimedIdentifier and LocalIdentifier must be the same when IsIdentifierSelect is true. 的本地化字符串。
        /// </summary>
        internal static string IdentifierSelectRequiresMatchingIdentifiers {
            get {
                return ResourceManager.GetString("IdentifierSelectRequiresMatchingIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The openid.identity and openid.claimed_id parameters must either be both present or both absent from the message. 的本地化字符串。
        /// </summary>
        internal static string IdentityAndClaimedIdentifierMustBeBothPresentOrAbsent {
            get {
                return ResourceManager.GetString("IdentityAndClaimedIdentifierMustBeBothPresentOrAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Provider requested association type &apos;{0}&apos; and session type &apos;{1}&apos;, which are not compatible with each other. 的本地化字符串。
        /// </summary>
        internal static string IncompatibleAssociationAndSessionTypes {
            get {
                return ResourceManager.GetString("IncompatibleAssociationAndSessionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (Contact: {1}, Reference: {2}) 的本地化字符串。
        /// </summary>
        internal static string IndirectErrorFormattedMessage {
            get {
                return ResourceManager.GetString("IndirectErrorFormattedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot encode &apos;{0}&apos; because it contains an illegal character for Key-Value Form encoding.  (line {1}: &apos;{2}&apos;) 的本地化字符串。
        /// </summary>
        internal static string InvalidCharacterInKeyValueFormInput {
            get {
                return ResourceManager.GetString("InvalidCharacterInKeyValueFormInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid XmlDSig signature on XRDS document. 的本地化字符串。
        /// </summary>
        internal static string InvalidDSig {
            get {
                return ResourceManager.GetString("InvalidDSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot decode Key-Value Form because a line was found without a &apos;{0}&apos; character.  (line {1}: &apos;{2}&apos;) 的本地化字符串。
        /// </summary>
        internal static string InvalidKeyValueFormCharacterMissing {
            get {
                return ResourceManager.GetString("InvalidKeyValueFormCharacterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The scheme must be http or https but was &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidScheme {
            get {
                return ResourceManager.GetString("InvalidScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is not a valid URI. 的本地化字符串。
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not a recognized XRI format. 的本地化字符串。
        /// </summary>
        internal static string InvalidXri {
            get {
                return ResourceManager.GetString("InvalidXri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The OpenID Provider issued an assertion for an Identifier whose discovery information did not match.  
        ///Assertion endpoint info: 
        ///{0}
        ///Discovered endpoint info:
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string IssuedAssertionFailsIdentifierDiscovery {
            get {
                return ResourceManager.GetString("IssuedAssertionFailsIdentifierDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list of keys do not match the provided dictionary. 的本地化字符串。
        /// </summary>
        internal static string KeysListAndDictionaryDoNotMatch {
            get {
                return ResourceManager.GetString("KeysListAndDictionaryDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; and &apos;{1}&apos; parameters must both be or not be &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MatchingArgumentsExpected {
            get {
                return ResourceManager.GetString("MatchingArgumentsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum time allowed to complete authentication has been exceeded.  Please try again. 的本地化字符串。
        /// </summary>
        internal static string MaximumAuthenticationTimeExpired {
            get {
                return ResourceManager.GetString("MaximumAuthenticationTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X.509 signing certificate issued to {0}, but a certificate for {1} was expected. 的本地化字符串。
        /// </summary>
        internal static string MisdirectedSigningCertificate {
            get {
                return ResourceManager.GetString("MisdirectedSigningCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing {0} element. 的本地化字符串。
        /// </summary>
        internal static string MissingElement {
            get {
                return ResourceManager.GetString("MissingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No recognized association type matches the requested length of {0}. 的本地化字符串。
        /// </summary>
        internal static string NoAssociationTypeFoundByLength {
            get {
                return ResourceManager.GetString("NoAssociationTypeFoundByLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No recognized association type matches the requested name of &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string NoAssociationTypeFoundByName {
            get {
                return ResourceManager.GetString("NoAssociationTypeFoundByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unless using transport layer encryption, &quot;no-encryption&quot; MUST NOT be used. 的本地化字符串。
        /// </summary>
        internal static string NoEncryptionSessionRequiresHttps {
            get {
                return ResourceManager.GetString("NoEncryptionSessionRequiresHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No identifier has been set. 的本地化字符串。
        /// </summary>
        internal static string NoIdentifierSet {
            get {
                return ResourceManager.GetString("NoIdentifierSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No XRDS document containing OpenID relying party endpoint information could be found at {0}. 的本地化字符串。
        /// </summary>
        internal static string NoRelyingPartyEndpointDiscovered {
            get {
                return ResourceManager.GetString("NoRelyingPartyEndpointDiscovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diffie-Hellman session type &apos;{0}&apos; not found for OpenID {1}. 的本地化字符串。
        /// </summary>
        internal static string NoSessionTypeFound {
            get {
                return ResourceManager.GetString("NoSessionTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation is not supported by serialized authentication responses.  Try this operation from the LoggedIn event handler. 的本地化字符串。
        /// </summary>
        internal static string NotSupportedByAuthenticationSnapshot {
            get {
                return ResourceManager.GetString("NotSupportedByAuthenticationSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No OpenID endpoint found. 的本地化字符串。
        /// </summary>
        internal static string OpenIdEndpointNotFound {
            get {
                return ResourceManager.GetString("OpenIdEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No OpenID url is provided. 的本地化字符串。
        /// </summary>
        internal static string OpenIdTextBoxEmpty {
            get {
                return ResourceManager.GetString("OpenIdTextBoxEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This operation is only allowed when IAuthenticationResponse.State == AuthenticationStatus.SetupRequired. 的本地化字符串。
        /// </summary>
        internal static string OperationOnlyValidForSetupRequiredState {
            get {
                return ResourceManager.GetString("OperationOnlyValidForSetupRequiredState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenID popup window or iframe did not recognize an OpenID response in the request. 的本地化字符串。
        /// </summary>
        internal static string PopupRedirectMissingResponse {
            get {
                return ResourceManager.GetString("PopupRedirectMissingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An positive OpenID assertion was received from OP endpoint {0} and was rejected based on this site&apos;s security settings. 的本地化字符串。
        /// </summary>
        internal static string PositiveAssertionFromNonQualifiedProvider {
            get {
                return ResourceManager.GetString("PositiveAssertionFromNonQualifiedProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find the signing secret by the handle &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PrivateRPSecretNotFound {
            get {
                return ResourceManager.GetString("PrivateRPSecretNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} property must be set first. 的本地化字符串。
        /// </summary>
        internal static string PropertyNotSet {
            get {
                return ResourceManager.GetString("PropertyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This property value is not supported by this control. 的本地化字符串。
        /// </summary>
        internal static string PropertyValueNotSupported {
            get {
                return ResourceManager.GetString("PropertyValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to determine the version of the OpenID protocol implemented by the Provider at endpoint &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ProviderVersionUnrecognized {
            get {
                return ResourceManager.GetString("ProviderVersionUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An HTTP request to the realm URL ({0}) resulted in a redirect, which is not allowed during relying party discovery. 的本地化字符串。
        /// </summary>
        internal static string RealmCausedRedirectUponDiscovery {
            get {
                return ResourceManager.GetString("RealmCausedRedirectUponDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry.  This site only accepts OpenIDs that are HTTPS-secured, but {0} is not a secure Identifier. 的本地化字符串。
        /// </summary>
        internal static string RequireSslNotSatisfiedByAssertedClaimedId {
            get {
                return ResourceManager.GetString("RequireSslNotSatisfiedByAssertedClaimedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The response is not ready.  Use IsResponseReady to check whether a response is ready first. 的本地化字符串。
        /// </summary>
        internal static string ResponseNotReady {
            get {
                return ResourceManager.GetString("ResponseNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 return_to &apos;{0}&apos; not under realm &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ReturnToNotUnderRealm {
            get {
                return ResourceManager.GetString("ReturnToNotUnderRealm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} parameter ({1}) does not match the actual URL ({2}) the request was made with. 的本地化字符串。
        /// </summary>
        internal static string ReturnToParamDoesNotMatchRequestUrl {
            get {
                return ResourceManager.GetString("ReturnToParamDoesNotMatchRequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ReturnTo property must not be null to support this operation. 的本地化字符串。
        /// </summary>
        internal static string ReturnToRequiredForOperation {
            get {
                return ResourceManager.GetString("ReturnToRequiredForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The openid.return_to parameter is required in the request message in order to construct a response, but that parameter was missing. 的本地化字符串。
        /// </summary>
        internal static string ReturnToRequiredForResponse {
            get {
                return ResourceManager.GetString("ReturnToRequiredForResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following parameter(s) are not included in the signature but must be: {0} 的本地化字符串。
        /// </summary>
        internal static string SignatureDoesNotIncludeMandatoryParts {
            get {
                return ResourceManager.GetString("SignatureDoesNotIncludeMandatoryParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid birthdate value.  Must be in the form yyyy-MM-dd. 的本地化字符串。
        /// </summary>
        internal static string SregInvalidBirthdate {
            get {
                return ResourceManager.GetString("SregInvalidBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type must implement {0}. 的本地化字符串。
        /// </summary>
        internal static string TypeMustImplementX {
            get {
                return ResourceManager.GetString("TypeMustImplementX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0} had unexpected value {1}. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedEnumPropertyValue {
            get {
                return ResourceManager.GetString("UnexpectedEnumPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected HTTP status code {0} {1} received in direct response. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedHttpStatusCode {
            get {
                return ResourceManager.GetString("UnexpectedHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unsolicited assertion cannot be sent for the claimed identifier {0} because this is not an authorized Provider for that identifier. 的本地化字符串。
        /// </summary>
        internal static string UnsolicitedAssertionForUnrelatedClaimedIdentifier {
            get {
                return ResourceManager.GetString("UnsolicitedAssertionForUnrelatedClaimedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rejecting unsolicited assertions requires a nonce store and an association store. 的本地化字符串。
        /// </summary>
        internal static string UnsolicitedAssertionRejectionRequiresNonceStore {
            get {
                return ResourceManager.GetString("UnsolicitedAssertionRejectionRequiresNonceStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsolicited assertions are not allowed at this relying party. 的本地化字符串。
        /// </summary>
        internal static string UnsolicitedAssertionsNotAllowed {
            get {
                return ResourceManager.GetString("UnsolicitedAssertionsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsolicited assertions are not allowed from 1.0 OpenID Providers. 的本地化字符串。
        /// </summary>
        internal static string UnsolicitedAssertionsNotAllowedFrom1xOPs {
            get {
                return ResourceManager.GetString("UnsolicitedAssertionsNotAllowedFrom1xOPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Providing a DateTime whose Kind is Unspecified is not allowed. 的本地化字符串。
        /// </summary>
        internal static string UnspecifiedDateTimeKindNotAllowed {
            get {
                return ResourceManager.GetString("UnspecifiedDateTimeKindNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized or missing canonicalization method. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedCanonicalizationMethod {
            get {
                return ResourceManager.GetString("UnsupportedCanonicalizationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This feature is unavailable due to an unrecognized channel configuration. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedChannelConfiguration {
            get {
                return ResourceManager.GetString("UnsupportedChannelConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized or missing signature method. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedSignatureMethod {
            get {
                return ResourceManager.GetString("UnsupportedSignatureMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The openid.user_setup_url parameter is required when sending negative assertion messages in response to immediate mode requests. 的本地化字符串。
        /// </summary>
        internal static string UserSetupUrlRequiredInImmediateNegativeResponse {
            get {
                return ResourceManager.GetString("UserSetupUrlRequiredInImmediateNegativeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The X.509 certificate used to sign this document is not trusted. 的本地化字符串。
        /// </summary>
        internal static string X509CertificateNotTrusted {
            get {
                return ResourceManager.GetString("X509CertificateNotTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XRI support has been disabled at this site. 的本地化字符串。
        /// </summary>
        internal static string XriResolutionDisabled {
            get {
                return ResourceManager.GetString("XriResolutionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XRI resolution failed. 的本地化字符串。
        /// </summary>
        internal static string XriResolutionFailed {
            get {
                return ResourceManager.GetString("XriResolutionFailed", resourceCulture);
            }
        }
    }
}
