//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss.Web.Auth.Messaging {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagingStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.Web.Auth.Messaging.MessagingStrings", typeof(MessagingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Argument&apos;s {0}.{1} property is required but is empty or null. 的本地化字符串。
        /// </summary>
        internal static string ArgumentPropertyMissing {
            get {
                return ResourceManager.GetString("ArgumentPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to send all message data because some of it requires multi-part POST, but IMessageWithBinaryData.SendAsMultipart was false. 的本地化字符串。
        /// </summary>
        internal static string BinaryDataRequiresMultipart {
            get {
                return ResourceManager.GetString("BinaryDataRequiresMultipart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HttpContext.Current is null.  There must be an ASP.NET request in process for this operation to succeed. 的本地化字符串。
        /// </summary>
        internal static string CurrentHttpContextRequired {
            get {
                return ResourceManager.GetString("CurrentHttpContextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataContractSerializer could not be initialized on message type {0}.  Is it missing a [DataContract] attribute? 的本地化字符串。
        /// </summary>
        internal static string DataContractMissingFromMessageType {
            get {
                return ResourceManager.GetString("DataContractMissingFromMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataContractSerializer could not be initialized on message type {0} because the DataContractAttribute.Namespace property is not set. 的本地化字符串。
        /// </summary>
        internal static string DataContractMissingNamespace {
            get {
                return ResourceManager.GetString("DataContractMissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An instance of type {0} was expected, but received unexpected derived type {1}. 的本地化字符串。
        /// </summary>
        internal static string DerivedTypeNotExpected {
            get {
                return ResourceManager.GetString("DerivedTypeNotExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directed message&apos;s Recipient property must not be null. 的本地化字符串。
        /// </summary>
        internal static string DirectedMessageMissingRecipient {
            get {
                return ResourceManager.GetString("DirectedMessageMissingRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given set of options is not supported by this web request handler. 的本地化字符串。
        /// </summary>
        internal static string DirectWebRequestOptionsNotSupported {
            get {
                return ResourceManager.GetString("DirectWebRequestOptionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while deserializing message {0}. 的本地化字符串。
        /// </summary>
        internal static string ErrorDeserializingMessage {
            get {
                return ResourceManager.GetString("ErrorDeserializingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred while sending a direct message or getting the response. 的本地化字符串。
        /// </summary>
        internal static string ErrorInRequestReplyMessage {
            get {
                return ResourceManager.GetString("ErrorInRequestReplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This exception was not constructed with a root request message that caused it. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotConstructedForTransit {
            get {
                return ResourceManager.GetString("ExceptionNotConstructedForTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This exception must be instantiated with a recipient that will receive the error message, or a direct request message instance that this exception will respond to. 的本地化字符串。
        /// </summary>
        internal static string ExceptionUndeliverable {
            get {
                return ResourceManager.GetString("ExceptionUndeliverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected {0} message but received no recognizable message. 的本地化字符串。
        /// </summary>
        internal static string ExpectedMessageNotReceived {
            get {
                return ResourceManager.GetString("ExpectedMessageNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The message expired at {0} and it is now {1}. 的本地化字符串。
        /// </summary>
        internal static string ExpiredMessage {
            get {
                return ResourceManager.GetString("ExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add extra parameter &apos;{0}&apos; with value &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ExtraParameterAddFailure {
            get {
                return ResourceManager.GetString("ExtraParameterAddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one of GET or POST flags must be present. 的本地化字符串。
        /// </summary>
        internal static string GetOrPostFlagsRequired {
            get {
                return ResourceManager.GetString("GetOrPostFlagsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This method requires a current HttpContext.  Alternatively, use an overload of this method that allows you to pass in information without an HttpContext. 的本地化字符串。
        /// </summary>
        internal static string HttpContextRequired {
            get {
                return ResourceManager.GetString("HttpContextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages that indicate indirect transport must implement the {0} interface. 的本地化字符串。
        /// </summary>
        internal static string IndirectMessagesMustImplementIDirectedProtocolMessage {
            get {
                return ResourceManager.GetString("IndirectMessagesMustImplementIDirectedProtocolMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insecure web request for &apos;{0}&apos; aborted due to security requirements demanding HTTPS. 的本地化字符串。
        /// </summary>
        internal static string InsecureWebRequestWithSslRequired {
            get {
                return ResourceManager.GetString("InsecureWebRequestWithSslRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} message required protections {{{1}}} but the channel could only apply {{{2}}}. 的本地化字符串。
        /// </summary>
        internal static string InsufficientMessageProtection {
            get {
                return ResourceManager.GetString("InsufficientMessageProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The customized binding element ordering is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidCustomBindingElementOrder {
            get {
                return ResourceManager.GetString("InvalidCustomBindingElementOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some part(s) of the message have invalid values: {0} 的本地化字符串。
        /// </summary>
        internal static string InvalidMessageParts {
            get {
                return ResourceManager.GetString("InvalidMessageParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The incoming message had an invalid or missing nonce. 的本地化字符串。
        /// </summary>
        internal static string InvalidNonceReceived {
            get {
                return ResourceManager.GetString("InvalidNonceReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An item with the same key has already been added. 的本地化字符串。
        /// </summary>
        internal static string KeyAlreadyExists {
            get {
                return ResourceManager.GetString("KeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} message does not support extensions. 的本地化字符串。
        /// </summary>
        internal static string MessageNotExtensible {
            get {
                return ResourceManager.GetString("MessageNotExtensible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value for {0}.{1} on member {1} was expected to derive from {2} but was {3}. 的本地化字符串。
        /// </summary>
        internal static string MessagePartEncoderWrongType {
            get {
                return ResourceManager.GetString("MessagePartEncoderWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while reading message &apos;{0}&apos; parameter &apos;{1}&apos; with value &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MessagePartReadFailure {
            get {
                return ResourceManager.GetString("MessagePartReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message parameter &apos;{0}&apos; with value &apos;{1}&apos; failed to base64 decode. 的本地化字符串。
        /// </summary>
        internal static string MessagePartValueBase64DecodingFault {
            get {
                return ResourceManager.GetString("MessagePartValueBase64DecodingFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while preparing message &apos;{0}&apos; parameter &apos;{1}&apos; for sending. 的本地化字符串。
        /// </summary>
        internal static string MessagePartWriteFailure {
            get {
                return ResourceManager.GetString("MessagePartWriteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This message has a timestamp of {0}, which is beyond the allowable clock skew for in the future. 的本地化字符串。
        /// </summary>
        internal static string MessageTimestampInFuture {
            get {
                return ResourceManager.GetString("MessageTimestampInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A non-empty string was expected. 的本地化字符串。
        /// </summary>
        internal static string NonEmptyStringExpected {
            get {
                return ResourceManager.GetString("NonEmptyStringExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A message response is already queued for sending in the response stream. 的本地化字符串。
        /// </summary>
        internal static string QueuedMessageResponseAlreadyExists {
            get {
                return ResourceManager.GetString("QueuedMessageResponseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This message has already been processed.  This could indicate a replay attack in progress. 的本地化字符串。
        /// </summary>
        internal static string ReplayAttackDetected {
            get {
                return ResourceManager.GetString("ReplayAttackDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This channel does not support replay protection. 的本地化字符串。
        /// </summary>
        internal static string ReplayProtectionNotSupported {
            get {
                return ResourceManager.GetString("ReplayProtectionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following required non-empty parameters were empty in the {0} message: {1} 的本地化字符串。
        /// </summary>
        internal static string RequiredNonEmptyParameterWasEmpty {
            get {
                return ResourceManager.GetString("RequiredNonEmptyParameterWasEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following required parameters were missing from the {0} message: {1} 的本地化字符串。
        /// </summary>
        internal static string RequiredParametersMissing {
            get {
                return ResourceManager.GetString("RequiredParametersMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The binding element offering the {0} protection requires other protection that is not provided. 的本地化字符串。
        /// </summary>
        internal static string RequiredProtectionMissing {
            get {
                return ResourceManager.GetString("RequiredProtectionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list is empty. 的本地化字符串。
        /// </summary>
        internal static string SequenceContainsNoElements {
            get {
                return ResourceManager.GetString("SequenceContainsNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The list contains a null element. 的本地化字符串。
        /// </summary>
        internal static string SequenceContainsNullElement {
            get {
                return ResourceManager.GetString("SequenceContainsNullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An HttpContext.Current.Session object is required. 的本地化字符串。
        /// </summary>
        internal static string SessionRequired {
            get {
                return ResourceManager.GetString("SessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message signature was incorrect. 的本地化字符串。
        /// </summary>
        internal static string SignatureInvalid {
            get {
                return ResourceManager.GetString("SignatureInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This channel does not support signing messages.  To support signing messages, a derived Channel type must override the Sign and IsSignatureValid methods. 的本地化字符串。
        /// </summary>
        internal static string SigningNotSupported {
            get {
                return ResourceManager.GetString("SigningNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream must have a known length. 的本地化字符串。
        /// </summary>
        internal static string StreamMustHaveKnownLength {
            get {
                return ResourceManager.GetString("StreamMustHaveKnownLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream&apos;s CanRead property returned false. 的本地化字符串。
        /// </summary>
        internal static string StreamUnreadable {
            get {
                return ResourceManager.GetString("StreamUnreadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream&apos;s CanWrite property returned false. 的本地化字符串。
        /// </summary>
        internal static string StreamUnwritable {
            get {
                return ResourceManager.GetString("StreamUnwritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected at most 1 binding element to apply the {0} protection, but more than one applied. 的本地化字符串。
        /// </summary>
        internal static string TooManyBindingsOfferingSameProtection {
            get {
                return ResourceManager.GetString("TooManyBindingsOfferingSameProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum allowable number of redirects were exceeded while requesting &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TooManyRedirects {
            get {
                return ResourceManager.GetString("TooManyRedirects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The array must not be empty. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedEmptyArray {
            get {
                return ResourceManager.GetString("UnexpectedEmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The empty string is not allowed. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedEmptyString {
            get {
                return ResourceManager.GetString("UnexpectedEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected direct response to use HTTP status code {0} but was {1} instead. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedHttpStatusCode {
            get {
                return ResourceManager.GetString("UnexpectedHttpStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message parameter &apos;{0}&apos; had unexpected value &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedMessagePartValue {
            get {
                return ResourceManager.GetString("UnexpectedMessagePartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected message {0} parameter &apos;{1}&apos; to have value &apos;{2}&apos; but had &apos;{3}&apos; instead. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedMessagePartValueForConstant {
            get {
                return ResourceManager.GetString("UnexpectedMessagePartValueForConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected message {0} but received {1} instead. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedMessageReceived {
            get {
                return ResourceManager.GetString("UnexpectedMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected message type received. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedMessageReceivedOfMany {
            get {
                return ResourceManager.GetString("UnexpectedMessageReceivedOfMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A null key was included and is not allowed. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedNullKey {
            get {
                return ResourceManager.GetString("UnexpectedNullKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A null or empty key was included and is not allowed. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedNullOrEmptyKey {
            get {
                return ResourceManager.GetString("UnexpectedNullOrEmptyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A null value was included for key &apos;{0}&apos; and is not allowed. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedNullValue {
            get {
                return ResourceManager.GetString("UnexpectedNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} or a derived type was expected, but {1} was given. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedType {
            get {
                return ResourceManager.GetString("UnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} property has unrecognized value {1}. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedEnumValue {
            get {
                return ResourceManager.GetString("UnrecognizedEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The URL &apos;{0}&apos; is rated unsafe and cannot be requested this way. 的本地化字符串。
        /// </summary>
        internal static string UnsafeWebRequestDetected {
            get {
                return ResourceManager.GetString("UnsafeWebRequestDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The HTTP verb &apos;{0}&apos; is unrecognized and unsupported. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedHttpVerb {
            get {
                return ResourceManager.GetString("UnsupportedHttpVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; messages cannot be received with HTTP verb &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedHttpVerbForMessageType {
            get {
                return ResourceManager.GetString("UnsupportedHttpVerbForMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redirects on POST requests that are to untrusted servers is not supported. 的本地化字符串。
        /// </summary>
        internal static string UntrustedRedirectsOnPOSTNotSupported {
            get {
                return ResourceManager.GetString("UntrustedRedirectsOnPOSTNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Web request to &apos;{0}&apos; failed. 的本地化字符串。
        /// </summary>
        internal static string WebRequestFailed {
            get {
                return ResourceManager.GetString("WebRequestFailed", resourceCulture);
            }
        }
    }
}
