//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiss.Web.Auth {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kiss.Web.Auth.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration-specified type {0} must be public, and is not. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationTypeMustBePublic {
            get {
                return ResourceManager.GetString("ConfigurationTypeMustBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration XAML reference to {0} requires a current HttpContext to resolve. 的本地化字符串。
        /// </summary>
        internal static string ConfigurationXamlReferenceRequiresHttpContext {
            get {
                return ResourceManager.GetString("ConfigurationXamlReferenceRequiresHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current IHttpHandler is not one of types: {0}.  An embedded resource URL provider must be set in your .config file. 的本地化字符串。
        /// </summary>
        internal static string EmbeddedResourceUrlProviderRequired {
            get {
                return ResourceManager.GetString("EmbeddedResourceUrlProviderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No current HttpContext was detected, so an {0} instance must be explicitly provided or specified in the .config file.  Call the constructor overload that takes an {0}. 的本地化字符串。
        /// </summary>
        internal static string StoreRequiredWhenNoHttpContextAvailable {
            get {
                return ResourceManager.GetString("StoreRequiredWhenNoHttpContextAvailable", resourceCulture);
            }
        }
    }
}
